apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_NAME: "ventas-app"
  APP_ENV: "production"
  APP_PORT: "8080"
  app.properties: |
    # Puerto de aplicación
    server.port=8080
    # Nivel de logs
    log.level=INFO
    # Tiempo máximo de espera
    timeout=30
