apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque # Tipo genérico para almacenar llaves/valor
# Permite escribir valores en texto plano
# Kubernetes automáticamente los convertirá a base64
# y los almacenerá internamente en "data"
stringData:
  DB_USER: admin
  DB_PASSWORD: super123
  API_KEY: abc-123-xyz
